[package]
name = "service"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
entity = { path = "../entity" }
sea-orm = { version = "1.1.0", features = ["debug-print", "runtime-tokio-rustls", "sqlx-postgres"] }
tracing = "*"
