version: "3"

tasks:
  default:
    cmds:
      - cargo run
  migrate-refresh:
    cmds:
      - sea-orm-cli migrate up
  migrate:
    cmds:
      - sea-orm-cli migrate up
  generate:
    cmds:
      - sea-orm-cli generate entity -o entity/src -l 
  download_specs:
    cmds:
      - ./make_specs.sh

  yaml_specs_to_app:
    cmds:
      - yq -p json -o yaml ./api_specs.json > "../ios/Sessioni Sotterranee/Sessioni Sotterranee/openapi.yaml"
