/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This interface was referenced by `Root`'s JSON-Schema
 * via the `definition` "RoleKind".
 */
export type RoleKind = "Admin" | "Audience" | "Musician";

export interface Root {
  CreateUser: CreateUser;
  User: User;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `Root`'s JSON-Schema
 * via the `definition` "CreateUser".
 */
export interface CreateUser {
  email: string;
  role_kind: RoleKind;
  username: string;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `Root`'s JSON-Schema
 * via the `definition` "User".
 */
export interface User {
  email: string;
  id: number;
  role_kind: RoleKind;
  username: string;
  [k: string]: unknown;
}
