//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "event")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub date: DateTimeWithTimeZone,
    pub title: String,
    pub description: Option<String>,
    pub genre: Option<String>,
    pub url: Option<String>,
    pub image: Option<String>,
    pub location: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::event_attending::Entity")]
    EventAttending,
    #[sea_orm(has_many = "super::event_interested::Entity")]
    EventInterested,
}

impl Related<super::event_attending::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventAttending.def()
    }
}

impl Related<super::event_interested::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventInterested.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
