//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::attending::Entity as Attending;
pub use super::interested::Entity as Interested;
pub use super::session::Entity as Session;
pub use super::user::Entity as User;
pub use super::weekly_event::Entity as WeeklyEvent;
