//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "street_jam_message")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub street_jam_id: i32,
    pub user_id: i32,
    pub date: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub message_text: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::street_jam::Entity",
        from = "Column::StreetJamId",
        to = "super::street_jam::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    StreetJam,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::street_jam::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StreetJam.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
