//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub log_to_id: String,
    pub username: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::event_attending::Entity")]
    EventAttending,
    #[sea_orm(has_many = "super::event_interested::Entity")]
    EventInterested,
    #[sea_orm(has_many = "super::main_message::Entity")]
    MainMessage,
    #[sea_orm(has_many = "super::street_jam::Entity")]
    StreetJam,
    #[sea_orm(has_many = "super::street_jam_message::Entity")]
    StreetJamMessage,
    #[sea_orm(has_many = "super::user_role::Entity")]
    UserRole,
}

impl Related<super::event_attending::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventAttending.def()
    }
}

impl Related<super::event_interested::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventInterested.def()
    }
}

impl Related<super::main_message::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MainMessage.def()
    }
}

impl Related<super::street_jam::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StreetJam.def()
    }
}

impl Related<super::street_jam_message::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StreetJamMessage.def()
    }
}

impl Related<super::user_role::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserRole.def()
    }
}

impl Related<super::role::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_role::Relation::Role.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_role::Relation::User.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
