//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::event_attending::Entity")]
    EventAttending,
    #[sea_orm(has_many = "super::event_interested::Entity")]
    EventInterested,
    #[sea_orm(has_many = "super::role::Entity")]
    Role,
    #[sea_orm(has_many = "super::street_jam::Entity")]
    StreetJam,
    #[sea_orm(has_many = "super::street_jam_message::Entity")]
    StreetJamMessage,
}

impl Related<super::event_attending::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventAttending.def()
    }
}

impl Related<super::event_interested::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventInterested.def()
    }
}

impl Related<super::role::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Role.def()
    }
}

impl Related<super::street_jam::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StreetJam.def()
    }
}

impl Related<super::street_jam_message::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StreetJamMessage.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
